pipeline {
    agent any
    tools {nodejs "nodejs-path"}
    stages {
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'npm run stylelint'
            }
        }
    }
    post {
        failure {
            echo "${GIT_COMMIT}"
            echo "${JOB_NAME}"
            echo "${$BUILD_NUMBER}"
        }
        success {
            echo "${GIT_COMMIT}"
            echo "${JOB_NAME}"
            echo "${$BUILD_NUMBER}"
        }
    }
}
