const sidebarItems = [
  { title: 'Accordion', link: 'accordion', default: true },
  { title: 'Action Bar', link: 'action-bar' },
  { title: 'Breadcrumb', link: 'breadcrumb' },
  { title: 'Button', link: 'button' },
  { title: 'Checkbox', link: 'checkbox' },
  {
    title: 'Content Switcher',
    link: 'content-switcher'
  },
  { title: 'Datatable', link: 'data-table' },
  { title: 'Datepicker', link: 'date-picker' },
  { title: 'Dropdown', link: 'dropdown' },
  { title: 'Fileuploader', link: 'file-uploader' },
  { title: 'Footer', link: 'footer' },
  { title: 'Form', link: 'form' },
  { title: 'Header', link: 'header' },
  { title: 'List', link: 'list' },
  { title: 'Loadingstate', link: 'loading-state' },
  { title: 'Modal', link: 'modal' },
  { title: 'Notification', link: 'notification' },
  { title: 'Numberinput', link: 'number-input' },
  { title: 'Overflowmenu', link: 'overflow-menu' },
  { title: 'Overlay', link: 'overlay' },
  { title: 'Pagination', link: 'pagination' },
  { title: 'Password', link: 'password' },
  {
    title: 'Progressindicator',
    link: 'progress-indicator'
  },
  { title: 'Radio', link: 'radio' },
  { title: 'Search', link: 'search' },
  { title: 'Select', link: 'select' },
  { title: 'Sidebar', link: 'sidebar' },
  { title: 'Slider', link: 'slider' },
  { title: 'Spinner', link: 'spinner' },
  { title: 'Tab', link: 'tab' },
  { title: 'Tag', link: 'tag' },
  { title: 'Textarea', link: 'textarea' },
  { title: 'Textinput', link: 'textinput' },
  { title: 'Tile', link: 'tile' },
  { title: 'Timepicker', link: 'time-picker' },
  { title: 'Toast', link: 'toast' },
  { title: 'Toggle', link: 'toggle' },
  { title: 'Toolbar', link: 'toolbar' },
  { title: 'Tooltip', link: 'tooltip' },
  { title: 'Tree', link: 'tree' }
];

export default sidebarItems;
