const sidebarItems = [
  { title: 'Accordion', link: 'accordion' },
  { title: 'Actionbar', link: 'actionbar' },
  { title: 'Breadcrumb', link: 'breadcrumb' },
  { title: 'Button', link: 'button' },
  { title: 'Checkbox', link: 'checkbox' },
  { title: 'Codesnippet', link: 'codesnippet' },
  { title: 'Contentswitcher', link: 'contentswitcher' },
  { title: 'Datatable', link: 'datatable' },
  { title: 'Datepicker', link: 'datepicker' },
  { title: 'Dropdown', link: 'dropdown' },
  { title: 'Fileuploader', link: 'fileuploader' },
  { title: 'Footer', link: 'footer' },
  { title: 'Form', link: 'form' },
  { title: 'Header', link: 'header' },
  { title: 'Inlineedit', link: 'inlineedit' },
  { title: 'Inpagenavigation', link: 'inpagenavigation' },
  { title: 'List', link: 'list' },
  { title: 'Loadingstate', link: 'loadingstate' },
  { title: 'Modal', link: 'modal' },
  { title: 'Notification', link: 'notification' },
  { title: 'Numberinput', link: 'numberinput' },
  { title: 'Overflowmenu', link: 'overflowmenu' },
  { title: 'Overlay', link: 'overlay' },
  { title: 'Pagination', link: 'pagination' },
  { title: 'Password', link: 'password' },
  { title: 'Progressindicator', link: 'progressindicator' },
  { title: 'Radio', link: 'radio' },
  { title: 'Search', link: 'search' },
  { title: 'Select', link: 'select' },
  { title: 'Sidebar', link: 'sidebar' },
  { title: 'Slider', link: 'slider' },
  { title: 'Spinner', link: 'spinner' },
  { title: 'Tab', link: 'tab' },
  { title: 'Tag', link: 'tag' },
  { title: 'Textarea', link: 'textarea' },
  { title: 'Textinput', link: 'textinput' },
  { title: 'Tile', link: 'tile' },
  { title: 'Timepicker', link: 'timepicker' },
  { title: 'Toast', link: 'toast' },
  { title: 'Toggle', link: 'toggle' },
  { title: 'Toolbar', link: 'toolbar' },
  { title: 'Tooltip', link: 'tooltip' },
  { title: 'Tree', link: 'tree' }
];

export default sidebarItems;
